"""initial_schema

Revision ID: 4b8cd2c5502d
Revises: 
Create Date: 2026-08-15 00:06:50.415013

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b8cd2c5502d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('analysis_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('stock_name', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('signal', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('llm_provider', sa.String(length=48), nullable=False),
    sa.Column('quick_think_llm', sa.String(length=96), nullable=False),
    sa.Column('deep_think_llm', sa.String(length=96), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_tasks_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_tasks_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_watchlist_user_ticker')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))

    op.drop_table('watchlist')
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_trade_date'))
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_ticker'))
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_status'))

    op.drop_table('analysis_tasks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
